### ISSUE TITLE
Jobs dying after a full wind down

### ISSUE THREAD

**Issue by djf604** [Parsl/parsl#216] opened 2018-04-19 15:23 UTC
Given the following code:

```python
@App('python', dfk)
def small_computation(*args, **kwargs):
    import random
    import time
    time.sleep(random.randint(5, 30))

futs = [small_computation() for _ in range(20)]
for fut in futs:
    fut.result()

time.sleep(20)

futs = [small_computation() for _ in range(20)]
for fut in futs:
    fut.result()
```

The second block of `small_computation()` tasks are randomly failing, while all of the first block of `small_computation()` tasks complete successfully.

It may have something to do with assigning tasks to engines that are already killed. I'm not sure if this is a deterministic problem.

**Comment by kylechard** [comment] 2018-09-18 19:09
Likely caused by scale in issues?

**Comment by hategan** [comment] 2019-10-02 23:27
I can't reproduce this with a recent version of Parsl. Is this still an issue?

**Comment by yadudoc** [comment] 2019-10-03 00:08
This should no longer be a problem with the `HighThroughputExecutor`. Closing.

**Closed by yadudoc** 2019-10-03 00:08 UTC
Labels: enhancement
