### ISSUE TITLE
ipp shutdown is unreliable

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#299] opened 2018-05-23 20:53 UTC
When `pytest --basic` runs, a bunch of ipcontrollers and other related things are left behind after pytest completes.

There are about 51 ipcontroller processes left (according to `ps ax`) after a test run on my laptop (out of a peak of about 320), as well as assorted ipengines and scripts.

~~I've had a bit of a fiddle and it looks like making the shutdown code wait a lot longer (on the order of minutes) for shutdowns to happen makes shutdowns much cleaner, although pytests exit phase then takes 20 minutes(!) as the number of ipcontroller processes ramps down fairly linearly over that period. Demo patch for that upcoming.~~ Turns out it doesn't actually reduce the number controllers/engines left at the end. It just waits longer for them to (not) respond to TERM.

**Comment by annawoodard** [comment] 2018-05-23 22:12
Is this a duplicate of #271? I don't think we should consider the problem of IPP not shutting down properly as a specific issue with pytest-- I think pytest just shows the problem more dramatically. `cleanup` is registered with atexit, so no matter what pytest does, if it is working properly, I would expect the engines to be cleaned up.

**Comment by kylechard** [comment] 2018-07-23 20:13
Duplicate.

**Closed by kylechard** 2018-07-23 20:13 UTC
