### ISSUE TITLE
Make naming conventions consistent

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#109] opened 2018-03-07 15:47 UTC
Since conventions are arbitrary, I do not have strong opinions about which are best; I think we should pick whatever is most common in the community and be consistent. We use a mix of naming styles. Consider the DFK constructor:
```
def __init__(self, config=None, executors=None, lazy_fail=True, appCache=True, rundir=None, fail_retries=2, checkpointFiles=None):
```

This mixes lowercase (rundir), lowercase with underscores (lazy_fail, fail_retries), and mixed case (appCache, checkpointFiles). I've seen a few cases of users making mistakes because they mixed up naming styles, so I think that even though it would require some existing user workflows to be updated, it might be worth it to move to a consistent style (and do so ASAP to minimize disruption). PEP-8 discourages mixedCase, so I vote we stick to: ClassName, ExceptionName, GLOBAL_CONSTANT_NAME, and lowercase_with_underscores for everything else.

I vaguely remember discussing this and I think we're already all in agreement, but I wanted to open an issue to keep track of this.

**Comment by annawoodard** [comment] 2018-03-07 16:03
I'll wait for feedback; if there are objections to making this change, I'll just close the issue, otherwise, I can implement this.

**Comment by danielskatz** [comment] 2018-03-07 16:45
I think this is a great idea, and we have talked about it before - the issue is that it may break backward compatibility, so we need to plan it carefully.

maybe we can talk about this next week while I am there?

**Comment by annawoodard** [comment] 2018-03-07 17:31
Sounds good!

**Comment by kylechard** [comment] 2018-03-07 18:11
Agreed on trying to be consistent and I also favor your approach " ClassName, ExceptionName, GLOBAL_CONSTANT_NAME, and lowercase with underscores for everything else"

**Comment by yadudoc** [comment] 2018-07-03 16:07
@annawoodard Can we close this one ?

**Closed** 2018-07-03 16:11 UTC
