### ISSUE TITLE
Harmonize resource allocation specification between WorkQueue and RCT

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#2415] opened 2022-08-19 16:40 UTC
Two of the execution providers for Parsl, WQ and RCT, support defining resource requirements for task but do so in different ways.

WQ looks for a single `parsl_resource_specification` keyword (see [docs](https://parsl.readthedocs.io/en/1.2.0/userguide/configuring.html#heterogeneous-resources)) that contains all of the components of the specifications and RCT expects a different keyword argument for each component (see [code](https://github.com/radical-cybertools/radical.pilot/blob/174d44e50be680ada9e63dfa1b55cf98021e78db/src/radical/pilot/agent/executing/parsl_rp.py#L252)).

We should combine both how the resources are passed (single kwargs vs many) and the terms used in each. 

Tagging the RCT team - @AymenFJA @mturilli
Tagging the WQ team - @btovar @tphung3

**Comment by AymenFJA** [comment] 2022-08-19 16:54
@WardLT , we used to ignore the `resource_specification` that is coming from `Parsl_dfk` as our executor is based on the `HTEX` executor that did not support resource specifications on the task-level. We should have a look again, and it should not be a problem to translate whatever resource specifications coming from Parsl on the task-level to RP. Keep in mind RP has more granular resource requirements on the task-level that need to be satisfied before launching the tasks.

**Comment by benclifford** [comment] 2022-09-06 09:02
Based on my experience adding `parsl_resource_specification` into htex as a prototype for prioritised queueing, I'm mostly of the opinion that where parsl is right now:

* resource specifications should all happen in a `parsl_resource_specification` parameter - so that it is the only thing that needs to change based on environment
* the contents of the resource specification dictionary can be executor specific: each executor is different enough that it doesn't make sense (to me) to force things into a standardised schema. (executors being different is a feature, not a bug)
* if, informally, you see resource attributes in the WQ executor which correspond to RCT attributes, then reuse the same name if it makes sense

**Comment by benclifford** [comment] 2022-09-06 09:08
(as a further example of why we shouldn't standardise on a fixed schema, a parsl executor submitting into funcX would likely need resource specifications of endpoint ID and container ID for each task, which doesn't make sense at all for Work Queue)

**Comment by benclifford** [comment] 2023-11-14 21:14
@AymenFJA I guess we should revisit this issue in light of recently merged radical pilot executor

**Comment by AymenFJA** [comment] 2023-11-15 14:47
> @AymenFJA I guess we should revisit this issue in light of recently merged radical pilot executor

@benclifford, thanks for raising this again. I agree, about unifying the task (app) resource specification by using `parsl_resource_specification` dictionary. Definitely, this special keyword argument would be RP specific just like in WQ.

**Comment by benclifford** [comment] 2023-11-17 11:28
fixed by #2962

**Closed by benclifford** 2023-11-17 11:28 UTC
Labels: enhancement
