### ISSUE TITLE
Running on a local cluster

### ISSUE THREAD

**Issue by gordonwatts** [Parsl/parsl#670] opened 2018-12-03 07:58 UTC
I'd like to have parsl push jobs out to a small cluster we've got in the HEP group. About 120 cores, split over about 10 machines. There is no batch manager or similar.

The pilot model seemed appropriate. I was thinking to use the IPyParallelExecutor, and then have each on a seperate note.

However, I don't know what to use for a provider. LocalProvider seems like what I want - tho it needs to be on another machine. I tried to hack it by giving it an SSHChannel, but that didn't work.

Here is the configuration I've been playing with:

        remote_config = Config(
            executors=[
                IPyParallelExecutor(
                    label='remote_ipp',
                    provider=LocalProvider(
                        min_blocks=1,
                        init_blocks=1,
                        max_blocks=4,
                        tasks_per_node=2,
                        nodes_per_block=1,
                        parallelism=0.5,
                        channel=SSHChannel(hostname=m)
                    )
                ) for m in args.remote
            ]
        )
        parsl.load(remote_config)

If I remove the "channel=" line, btw, then my code runs just fine. All the jobs seem to execute without difficulty. Though the IPy executor generates a huge number of log messages!

I'm a totally newbee here - This is the first time I've used parsl. Very nice, btw, in about 2 hours I had something up and running on a single machine. Took me another 2 days to make it "robust". :-)

**Comment by annawoodard** [comment] 2018-12-03 16:50
Welcome @gordonwatts!!!

Your approach sounds reasonable to me. What error are you getting when you run with `channel=...`? Note also that you should use a unique label for each executor.

**Comment by gordonwatts** [comment] 2018-12-03 18:18
Ops - thanks for the note about the label. I would have run into that as soon as I tried more than one machine.

So, I did see some crashes. But what made me think I was really taking the wrong approach was that I ran this on a machine called tev01. And had it connect to tev02 for running. But the processes and jobs were actually executing on tev01.

I will capture a log file for you. I am sure I'm doing something wrong here - I didn't find a working example, so I was looking through the source code trying to figure out how to make this work.

**Comment by danielskatz** [comment] 2018-12-03 18:19
I think your idea of a "local cluster" is probably different than ours, so this will probably take some exchange to understand fully

**Comment by annawoodard** [comment] 2018-12-03 18:21
Awesome job, @gordonwatts, sounds like you've discovered a mode of running we haven't tried before. You're a trailblazer! @yadudoc is going to test this on our side. It sounds like there may be some bugs when using LocalProvider+SSHChannel.

**Comment by gordonwatts** [comment] 2018-12-03 18:30
The docs for LocalProvider say for "running on localhost" - so I was thinking LocalProvider was the wrong thing for me to use. Log file in a second. I can also point you to the source code if you think it will help. But it is a mess (first time I've used this, and I always get stuck in monad hell when working with futures).

**Comment by gordonwatts** [comment] 2018-12-03 20:34
[remote_test.log](https://github.com/Parsl/parsl/files/2641157/remote_test.log) - the log file.

The source file: https://gitlab.cern.ch/gwatts/DistributedRunner/blob/master/pyscripts/run_distributed.py

That should be visible. The part that sets up the config is way at the bottom.

Given this relies on other code and some data that is a pain to fetch, I'm afraid you can't really run it yourself. Comments on style, etc., are welcome.

Thanks for helping sort this out.

**Comment by gordonwatts** [comment] 2018-12-03 20:39
Oh, and what do I mean by cluster here?

Typical small university group. We have about 120 cores on ~10 machines. They aren't running any sophisticated batch processing software (not even Condor in this instance). They are all well connected and have access to ~100 TB of disk space. This is a small analysis cluster. Each node has the same view of the disk system.

I have to run on about a TB of data. Linear processing takes about 24 or so hours. With those cores I should be able to do much better. But I need a way to coordinate things. We've used dask before, but I thought parsl seemed perfect. Indeed, other than the monad problem, it seems very natural.

Does that help, @danielskatz in defining what I'm thinking about?

BTW, you are going for extreme performance for some HTC computers (I saw a reference to 1000's of tasks per second). For this that doesn't matter. I already get a good speed up running on one node with many threads. Running on 10 nodes would be mean what took one day would take about a half hour or so.

**Comment by danielskatz** [comment] 2018-12-03 20:52
Thanks - we typically think of a cluster as a set of nodes with some scheduling software, and I think your cluster is really just a set of nodes, so in our terminology, each of your nodes would be a cluster for us.

**Comment by annawoodard** [comment] 2018-12-03 21:00
@gordonwatts, we think @yadudoc was able to reproduce your issue-- it's a bug on our side when using LocalProvider+SSHChannel. He's working on a fix and should have it for ya by later today.

**Comment by gordonwatts** [comment] 2018-12-03 21:10
@danielskatz - yes, that makes sense. For you, a cluster is a scheduling end-point. In my world, then, each node has to be individually scheduled.

@annawoodard and @yadudoc - Ah, that is awesome, thanks so much for the fast response! I'm using 0.6.1 so I assume this would be off the head. Do you have best practices for using this as a library you download vs a pip-install?

**Comment by gordonwatts** [comment] 2018-12-03 22:48
Perfect, thanks! I do use conda for quite a bit of stuff. I like the virtual env quite a bit, though I end up usually installing a lot of stuff into them that the base environment has. :-) Will definitely do it this way for that. I'm going to be busy the rest of the day here, but after dinner, I'll check back in and try it out if it is ready!

**Comment by annawoodard** [comment] 2018-12-03 23:33
The new branch is ready for testing. Let us know how it goes. Thanks for trying it out, @gordonwatts!

Note that as @yadudoc mentioned in #673, there are some subtleties that may leave the IPP workers lingering around for a few minutes before being cleaned up. Also note: the next Parsl release will include two new executors-- `HighThroughputExecutor` (which we would like to start pushing as a more robust `IPyParallelExecutor` alternative) and `ExtremeScaleExecutor` (mpi-based, not relevant to your use-case). For now, running with `LocalProvider`+`SSHChannel` as you are doing, cleanup *will not* work with `HighThroughputExecutor`. This doesn't affect you at the moment, since you're using IPP-- just be aware that, in case you venture out into the bleeding edge, we have a bit more tinkering to do to get cleanup working properly with `LocalProvider`+`SSHChannel` + `HighThroughputExecutor`.

**Comment by gordonwatts** [comment] 2018-12-04 07:19
I don't know if this indicates a problem in your setup script or somewhere else, but libsubmit didn't get installed correctly by your setup script:

```
(parsl) -bash-4.2$ time python ../../DistributedRunner/build/run_distributed.py test/tracks 4500-4501 junkdir2 tracks.root --cmd_prefix "source $ATLAS_LOCAL_ROOT_BASE/user/atlasL
ocalSetup.sh" --cmd_prefix "lsetup \"root recommended\""
Traceback (most recent call last):
  File "../../DistributedRunner/build/run_distributed.py", line 224, in <module>
    from libsubmit.providers.local.local import LocalProvider
ModuleNotFoundError: No module named 'libsubmit'
```

**Comment by gordonwatts** [comment] 2018-12-04 07:42
Ok. This new version... So I can't get the in-memory executor to run yet. It seems to be doing something funny with path's and LD_LIBRARY_PATHS and I'm now getting libstdc++ problems - it seems to be picking up the wrong thing. I assume this is a config problem on my end and I need to spend more than 15 minutes tracking it down. :-)

But I thought I'd just try the IPP provider and I got the following:

```
Traceback (most recent call last):
  File "../../DistributedRunner/build/run_distributed.py", line 274, in <module>
    parsl.load(remote_config)
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/dflow.py", line 1021, in load
    cls._dfk = DataFlowKernel(config)
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/dflow.py", line 172, in __init__
    executor.provider.channel.makedirs(executor.provider.channel.script_dir, exist_ok=True)
AttributeError: 'SSHChannel' object has no attribute 'makedirs'
```

If this was working for you, then the simple install instructions above must not be enough. Oh - wait - I am using python 3.7. Could that make a difference? I wouldn't think so.

**Comment by gordonwatts** [comment] 2018-12-04 08:11
Had some trouble with the change in the way stdout and stderr are treated in this new version (comment left in #538). That along with a specific LD_LIBRARY_PATH I had to specify (which I do not understand, but ok), got the local thread provider working properly. However, the error I detailed just above still exists when I try to use the SSHChannel.

**Comment by yadudoc** [comment] 2018-12-04 08:12
I believe we are seeing libsubmit+parsl incompatibility here. We merged libsubmit back into parsl, so you should update module import paths in your script. For eg [here](https://gitlab.cern.ch/gwatts/DistributedRunner/blob/master/pyscripts/run_distributed.py#L224) you should replace `from libsubmit.providers.local.local import LocalProvider` with `from parsl.providers import LocalProvider` and `from libsubmit.channels import SSHChannel` to `from parsl.channels import SSHChannel`.

The makedirs issue is most likely from a mismatch in the interface between 0.5.0 libsubmit and latest Parsl. I'd recommend removing libsubmit and retrying with the updated scripts.

I think we are pretty close to getting this working!

**Comment by gordonwatts** [comment] 2018-12-04 08:52
Ah- yes - i saw that in some samples last night when I was poking around in the parsl github repro. I should have remembered. Ok - that fixed that.

- `tasks_per_node` is no longer there. I've not investigated a replacement yet becuase:

```
Traceback (most recent call last):
  File "../../DistributedRunner/build/run_distributed.py", line 285, in <module>
    run_list = get_run_list(args.run_list, args.cmd_prefix)
  File "../../DistributedRunner/build/run_distributed.py", line 216, in get_run_list
    v = run_bash_command("%s echo NOWAYDUDE && %s %s" % (pCmd, exe_dir, runinfo), stdout='get_run_list.log').result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/futures.py", line 126, in parent_callback
    res = executor_fu.result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/dflow.py", line 257, in handle_exec_update
    res = future.result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/ipyparallel-6.2.3-py3.7.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: ModuleNotFoundError(No module named 'parsl.app.bash')
```
I suspect this is because I'm using this second conda environment, so it is running with the old parsl installed. How can I tell it to do a "conda activate parsl" before anything gets going in the SSHChannel?

**Comment by annawoodard** [comment] 2018-12-04 17:35
(facepalm) I'm so sorry @gordonwatts, it totally slipped my mind that we needed to head-proof your script. Here's a start, sorry you probably already got this on your own after a lot of pain and poking around. Imports should be:

```
from parsl.executors.threads import ThreadPoolExecutor
from parsl.executors.ipp import IPyParallelExecutor
from parsl.providers.local.local import LocalProvider
from parsl.channels import SSHChannel
from multiprocessing import cpu_count
```

remote config should be something like:
```
        remote_config = Config(
            executors=[
                IPyParallelExecutor(
                    label='remote_ipp_{}'.format(m),
                    worker_init='conda activate parsl',
                    workers_per_node=4,
                    provider=LocalProvider(
                        min_blocks=1,
                        init_blocks=1,
                        max_blocks=4,
                        nodes_per_block=1,
                        parallelism=0.5,
                        channel=SSHChannel(hostname=m)
                    )
                ) for m in args.remote
            ]
        )
```

note that `worker_init` is run before the worker is started, and `tasks_per_node` in the provider has been replaced by `workers_per_node` in the executor.

> I suspect this is because I'm using this second conda environment, so it is running with the old parsl installed.

I would recommend deleting parsl and libsubmit everywhere you can find them and starting over with a clean conda env.

**Comment by annawoodard** [comment] 2018-12-04 18:52
Note the edit above, `worker_init` should be in the provider.

**Comment by gordonwatts** [comment] 2018-12-05 00:18
Hmmm - there is nothing like `worker_init` in `IPyParallelExecutor` - is it attached to something else? At least not in the head of this branch.

    def __init__(self,
                 provider=LocalProvider(),
                 label='ipp',
                 working_dir=None,
                 controller=Controller(),
                 container_image=None,
                 engine_dir=None,
                 storage_access=None,
                 engine_debug_level=None,
                 workers_per_node=1,
                 managed=True):

Hmmm... Seems like it is an attribute of LocalProvider in your source code repro. Ah - less of a crash now! Lets see if that works!!

**Comment by gordonwatts** [comment] 2018-12-05 00:32
Ok - crash, again, because it couldn't find the parsl module:

```
(parsl) -bash-4.2$ time python ../../DistributedRunner/build/run_distributed.py test/tracks 4500-4501 junkdir tracks.root --cmd_prefix "source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh" --cmd_prefix "lsetup \"root recommended\"" --cmd_prefix "export TESTSTANDCONFIG=/phys/groups/tev/scratch3/users/gwatts/MATHUSLA/TestStandOffline/config" --cmd_prefix 'export LD_LIBRARY_PATH=/phys/groups/tev/scratch3/users/gwatts/MATHUSLA/TestStandOffline/build:$LD_LIBRARY_PATH' --remote tev02
/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/ipython-7.2.0-py3.7.egg/IPython/paths.py:48: UserWarning: Ignoring ~/.config/ipython in favour of ~/.ipython. Remove ~/.config/ipython to get rid of this message
  'get rid of this message').format(cu(xdg_ipdir), cu(ipdir)))
Traceback (most recent call last):
  File "../../DistributedRunner/build/run_distributed.py", line 287, in <module>
    run_list = get_run_list(args.run_list, args.cmd_prefix)
  File "../../DistributedRunner/build/run_distributed.py", line 216, in get_run_list
    v = run_bash_command("%s echo NOWAYDUDE && %s %s" % (pCmd, exe_dir, runinfo), stdout='get_run_list.log').result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/futures.py", line 126, in parent_callback
    res = executor_fu.result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/dflow.py", line 257, in handle_exec_update
    res = future.result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/ipyparallel-6.2.3-py3.7.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: ModuleNotFoundError(No module named 'parsl')
```

poking around (sorry, not 100% srue what I'm looking for), I see that there is a lot file in runinfo/000 and found parsl.log, which I think is the most useful?

```
(parsl) -bash-4.2$ cat parsl.log
2018-12-04 16:25:17 parsl.dataflow.dflow:82 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True,
    checkpoint_files=None,
    checkpoint_mode=None,
    checkpoint_period=None,
    data_management_max_threads=10,
    executors=[IPyParallelExecutor(
        container_image=None,
        controller=Controller(
            interfaces=None,
            ipython_dir='~/.ipython',
            log=True,
            mode='auto',
            port=None,
            port_range=None,
            profile='default',
            public_ip=None,
            reuse=False
        ),
        engine_debug_level=None,
        engine_dir=None,
        label='remote_ipp_tev02',
        managed=True,
        provider=LocalProvider(
            channel=SSHChannel(
                'tev02',
                envs={},
                password=None,
                script_dir=None,
                username=None
            ),
            cmd_timeout=30,
            init_blocks=1,
            launcher=SingleNodeLauncher(),
            max_blocks=4,
            min_blocks=1,
            nodes_per_block=1,
            parallelism=0.5,
            walltime='00:15:00',
            worker_init='conda activate parsl'
        ),
        storage_access=[],
        workers_per_node=10,
        working_dir=None
    )],
    lazy_errors=True,
    monitoring_config=None,
    retries=0,
    run_dir='runinfo',
    strategy='simple',
    usage_tracking=True
)
2018-12-04 16:25:17 parsl.dataflow.dflow:83 [INFO]  Parsl version: 0.6.2-a1
2018-12-04 16:25:17 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: True
2018-12-04 16:25:17 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2018-12-04 16:25:17 parsl.dataflow.dflow:123 [INFO]  Run id is: 27937f6e-1e36-45f2-8480-c1a7905de845
2018-12-04 16:25:17 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2018-12-04 16:25:19 parsl.executors.ipp_controller:83 [DEBUG]  Starting ipcontroller with 'ipcontroller --ipython-dir=/phys/groups/tev/scratch3/users/gwatts/MATHUSLA/TestStandOffline/build/runinfo/000 --ip=* --profile=remote_ipp_tev02   '
2018-12-04 16:25:21 parsl.executors.ipp:107 [DEBUG]  Waiting for /phys/groups/tev/scratch3/users/gwatts/MATHUSLA/TestStandOffline/build/runinfo/000/profile_remote_ipp_tev02/security/ipcontroller-client.json
2018-12-04 16:25:21 parsl.executors.ipp:123 [DEBUG]  Starting IPyParallelExecutor with provider:
LocalProvider(
    channel=SSHChannel(
        'tev02',
        envs={},
        password=None,
        script_dir='/phys/groups/tev/scratch3/users/gwatts/MATHUSLA/TestStandOffline/build/runinfo/000/submit_scripts',
        username=None
    ),
    cmd_timeout=30,
    init_blocks=1,
    launcher=SingleNodeLauncher(),
    max_blocks=4,
    min_blocks=1,
    nodes_per_block=1,
    parallelism=0.5,
    walltime='00:15:00',
    worker_init='conda activate parsl'
)
2018-12-04 16:25:21 parsl.providers.local.local:188 [DEBUG]  Not a localChannel, files need to be moved
2018-12-04 16:25:24 parsl.executors.ipp:242 [DEBUG]  Launched block 0:8346
2018-12-04 16:25:24 parsl.executors.ipp:249 [ERROR]  No execution provider available
2018-12-04 16:25:24 parsl.executors.ipp:132 [DEBUG]  Starting executor
2018-12-04 16:25:24 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: simple
2018-12-04 16:25:24 parsl.dataflow.dflow:669 [INFO]  Task 0 submitted for App remote_side_bash_executor, waiting on tasks []
2018-12-04 16:25:24 parsl.dataflow.dflow:679 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture at 0x7f1f0f22b4a8 state=pending>
2018-12-04 16:25:24 parsl.dataflow.dflow:472 [INFO]  Task 0 launched on executor remote_ipp_tev02
2018-12-04 16:25:27 parsl.dataflow.strategy:202 [DEBUG]  Executor remote_ipp_tev02 has 1 active tasks, 0/0/0 running/submitted/pending blocks, and 0 connected engines
2018-12-04 16:25:27 parsl.dataflow.strategy:256 [DEBUG]  Requesting 1 more blocks
2018-12-04 16:25:27 parsl.providers.local.local:188 [DEBUG]  Not a localChannel, files need to be moved
2018-12-04 16:25:29 parsl.dataflow.dflow:262 [ERROR]  Task 0 failed
Traceback (most recent call last):
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/parsl-0.6.2a1-py3.7.egg/parsl/dataflow/dflow.py", line 257, in handle_exec_update
    res = future.result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/phys/groups/tev/scratch3/users/gwatts/anaconda3/envs/parsl/lib/python3.7/site-packages/ipyparallel-6.2.3-py3.7.egg/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: ModuleNotFoundError(No module named 'parsl')
2018-12-04 16:25:29 parsl.dataflow.dflow:286 [INFO]  Task 0 failed after 0 retry attempts
2018-12-04 16:25:29 parsl.dataflow.dflow:784 [INFO]  DFK cleanup initiated
2018-12-04 16:25:29 parsl.dataflow.dflow:715 [INFO]  Summary of tasks in DFK:
2018-12-04 16:25:29 parsl.dataflow.dflow:746 [INFO]  Tasks in state States.failed: 0
2018-12-04 16:25:29 parsl.dataflow.dflow:753 [INFO]  End of summary
2018-12-04 16:25:29 parsl.dataflow.dflow:808 [INFO]  Terminating flow_control and strategy threads
2018-12-04 16:25:30 parsl.executors.ipp:242 [DEBUG]  Launched block 0:8636
2018-12-04 16:25:30 parsl.executors.ipp:249 [ERROR]  No execution provider available
2018-12-04 16:25:33 parsl.executors.ipp:295 [DEBUG]  IPP:Shutdown sequence: Attempting controller kill
2018-12-04 16:25:33 parsl.executors.ipp_controller:143 [DEBUG]  Controller exited with 0
2018-12-04 16:25:33 parsl.executors.ipp:305 [DEBUG]  Done with executor shutdown
2018-12-04 16:25:33 parsl.data_provider.data_manager:98 [DEBUG]  Done with executor shutdown
2018-12-04 16:25:33 parsl.dataflow.dflow:831 [INFO]  DFK cleanup complete
```

When I watch tev02 with `top` it looks like the `conda` command does actually execute. Perhaps the SSH channel isn't persistent? Or it isn't executed early enough, or it is executed as a sub-process, but the parent process isn't getting the benifit?

If there are other log files you'd like me to upload, let me know!

**Comment by annawoodard** [comment] 2018-12-05 02:58
Hi @gordonwatts! Any chance you could make one of us a temporary account to login to the cluster and poke around to try to pin down what's going on here? Alternatively (or in addition to), would you be up for jumping on a quick call tomorrow? Then we could also go through your script in case there were any questions/clarifications to make there. Finally, we hope the debugging output will be a bit more helpful with the new executor with its debug logging enabled, so you could try try adding these imports
```
from parsl.addresses import address_by_hostname
from parsl.executors import HighThroughputExecutor
```

and then tweaking the config as
```
     remote_config = Config(
            executors=[
                HighThroughputExecutor(
                    label='remote_htex_{}'.format(m),
                    cores_per_worker=1,
                    worker_debug=True,
                    address=address_by_hostname(),
                    provider=LocalProvider(
                        min_blocks=1,
                        init_blocks=1,
                        max_blocks=1,
                        nodes_per_block=1,
                        parallelism=0.5,
                        channel=SSHChannel(hostname=m),
                        worker_init='conda activate parsl',
                    )
                ) for m in args.remote
            ]
        )
```

**Comment by gordonwatts** [comment] 2018-12-05 10:40
Ok - looking at that debug file I was able to make some progress. Teh following works:

```
                        worker_init='source /phys/groups/tev/scratch3/users/gwatts/anaconda3/etc/profile.d/conda.sh && conda activate parsl',
```

And with that init, the IPEngine also works. So the issue was somehow my .bashrc wasn't getting executed.

**Comment by gordonwatts** [comment] 2018-12-05 10:49
So, now that painful bit is done, I think this can be closed - it works from the head! :-)

And I definately have some questions about what I'm doing, so if you want to chat tomorrow, reach out on slack!

**Comment by annawoodard** [comment] 2018-12-05 21:47
Awesome sleuthing @gordonwatts! Thanks for reporting the original issue and testing @yadudoc's fix! We'll be in touch on Slack about your other questions.

**Closed** 2018-12-05 21:47 UTC
Labels: bug
